name: goalkeeper
description: A simple Flutter app to help you achieve your goals!

version: 1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dynamic_theme:
  eva_icons_flutter:
  flutter_local_notifications: ^0.7.1
  flutter_speed_dial:
  path_provider:
  sqflite: ^1.1.5
  url_launcher:
#  simple_share:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter:
  uses-material-design: true
  assets:
      - assets/

flutter_icons:
  android: launcher_icon
#  adaptive_icon_background: "#00bcd4"
#  adaptive_icon_foreground: "#ff7043"
  image_path_android: assets/icon-android.png
  ios: true
  image_path_ios: assets/icon-ios.png